
[env]
TERM = "xterm-256color"

[font] 
size = 16.0

[font.normal] 
family = "JetbrainsMonoNerdFont" 
style = "Medium" 

[window] 
opacity = 1
# blur = true

[window.padding] 
x = 15
y = 0

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

